application:
  subdomain: handbrake
  background_task: true
  upstreams:
    - location: /
      backend: http://handbrake-server:9999/

services:
  handbrake-server:
    # upstream: ghcr.io/thenickoftime/handbrake-web-server:0.8.1
    user: root
    image: ghcr.io/thenickoftime/handbrake-web-server:0.8.1
    binds:
      - /lzcapp/var/data:/data
      - /lzcapp/var/video:/video
  handbrake-worker:
    # upstream: ghcr.io/thenickoftime/handbrake-web-worker:0.8.1
    image: ghcr.io/thenickoftime/handbrake-web-worker:0.8.1
    user: root
    environment:
      - WORKER_ID=handbrake-worker
      - SERVER_URL=handbrake-server
      - SERVER_PORT=9999
    depends_on:
      - handbrake-server
    binds:
      - /lzcapp/var/video:/video
