lzc-sdk-version: "0.1"
name: HandBrake
package: cloud.lazycat.app.handbrake
version: 0.7.3
description: 一个自托管的HandBrake Web平台
homepage: https://github.com/TheNickOfTime/handbrake-web
author: TheNickOfTime
application:
  subdomain: handbrake
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  routes:
    - /=http://handbrake-server.cloud.lazycat.app.handbrake.lzcapp:9999/
services:
  handbrake-server:
    image: registry.lazycat.cloud/czyt/thenickoftime/handbrake-web-server:f732a198cd6dbe28
    binds:
      - /lzcapp/var/data:/data
      - /lzcapp/var/video:/video
  handbrake-worker:
    image: registry.lazycat.cloud/czyt/thenickoftime/handbrake-web-worker:049954336420774c
    environment:
      - WORKER_ID=handbrake-worker
      - SERVER_URL=handbrake-server
      - SERVER_PORT=9999
    depends_on:
      - handbrake-server
    binds:
      - /lzcapp/var/video:/video
unsupported_platforms:
  - ios
  - android
